#pragma once
#include "axonforge/tensor.hpp"
#include <cstdint>
#include <limits>
#include <string>
#include <string_view>
#include <unordered_map>
#include <variant>
#include <vector>

namespace axonforge {

// ============================================================
// OpType — minimum complete set of primitive operations.
// Complex LLM ops (RoPE, SwiGLU) are decomposed during Lowering.
// ============================================================
enum class OpType : uint16_t {
    // --- Unary (element-wise) ---
    NEG, ABS, SQRT, EXP, LOG,
    RELU, SILU, GELU, SIGMOID, TANH,
    CAST,

    // --- Binary (element-wise, broadcast-aware) ---
    ADD, SUB, MUL, DIV, POW,
    MAX_ELEM, MIN_ELEM,

    // --- Reduce ---
    SUM, MEAN, MAX_REDUCE, MIN_REDUCE,

    // --- Movement (all O(1) — metadata-only until Contiguous) ---
    RESHAPE, PERMUTE, SLICE, PAD, CONTIGUOUS,
    BROADCAST_TO,

    // --- Linear algebra ---
    MATMUL,           // (M,K) × (K,N) → (M,N), broadcast batch dims
    MATMUL_SCALED,    // scaled_dot_product: Q*K^T/sqrt(d) with optional mask

    // --- Normalisation ---
    LAYER_NORM,
    RMS_NORM,

    // --- Attention helpers ---
    SOFTMAX,
    ROPE,             // Rotary Positional Embedding

    // --- Embedding ---
    EMBEDDING_LOOKUP,

    // --- Fused (generated by FusePass) ---
    FUSED_MATMUL_BIAS,
    FUSED_MATMUL_BIAS_ACT,
    FUSED_RMS_NORM_SCALE,

    CUSTOM = 0xFFFF,
};

[[nodiscard]] std::string_view op_type_name(OpType op) noexcept;

// ============================================================
// AttributeMap — key-value store for op hyper-parameters.
// ============================================================
using AttrValue = std::variant<int64_t, float, bool, std::string,
                               std::vector<int64_t>>;

class AttributeMap {
public:
    void set(std::string_view key, AttrValue value);
    [[nodiscard]] const AttrValue* get(std::string_view key) const noexcept;

    template<typename T>
    [[nodiscard]] T get_or(std::string_view key, T default_val) const {
        if (auto* v = get(key); v) {
            if (auto* p = std::get_if<T>(v)) return *p;
        }
        return default_val;
    }

private:
    std::unordered_map<std::string, AttrValue> data_;
};

// ============================================================
// TensorId / NodeId — integer handles into ComputeGraph tables.
// ============================================================
using TensorId = uint32_t;
using NodeId   = uint32_t;
static constexpr TensorId INVALID_TENSOR = std::numeric_limits<TensorId>::max();
static constexpr NodeId   INVALID_NODE   = std::numeric_limits<NodeId>::max();

// A dimension can be concrete (int64_t) or symbolic (string name).
using DimExpr       = std::variant<int64_t, std::string>;
using SymbolicShape = std::vector<DimExpr>;

// Tensor descriptor used inside the graph (may have symbolic dims).
struct TensorDesc {
    SymbolicShape shape;
    DType         dtype{DType::UNKNOWN};
    std::string   name;         // optional debug name
};

// One node in the computation DAG.
struct OpNode {
    NodeId          id{INVALID_NODE};
    OpType          op{OpType::CUSTOM};
    std::vector<TensorId> inputs;
    std::vector<TensorId> outputs;
    AttributeMap    attrs;
    std::string     name;       // optional debug name
};

// ============================================================
// ComputeGraph — the IR (DAG) of the model.
// ============================================================
class ComputeGraph {
public:
    // Add a tensor descriptor; returns its id.
    TensorId add_tensor(TensorDesc desc);

    // Add a node; returns its id.
    NodeId   add_node(OpNode node);

    // Mark tensors as graph inputs / outputs.
    void     set_inputs (std::vector<TensorId> ids);
    void     set_outputs(std::vector<TensorId> ids);

    [[nodiscard]] const TensorDesc& tensor_desc(TensorId id) const;
    [[nodiscard]] const OpNode&     node(NodeId id)          const;
    [[nodiscard]] const std::vector<OpNode>& nodes()    const noexcept;
    [[nodiscard]] const std::vector<TensorId>& inputs()  const noexcept;
    [[nodiscard]] const std::vector<TensorId>& outputs() const noexcept;

    // Instantiate symbolic dims with concrete values.
    // Returns a new graph with all DimExpr resolved to int64_t.
    [[nodiscard]] ComputeGraph
        instantiate(const std::unordered_map<std::string, int64_t>& bindings) const;

    // Topological order of node ids (cached).
    [[nodiscard]] const std::vector<NodeId>& topo_order() const;

    void clear();

private:
    std::vector<TensorDesc> tensors_;
    std::vector<OpNode>     nodes_;
    std::vector<TensorId>   graph_inputs_;
    std::vector<TensorId>   graph_outputs_;
    mutable std::vector<NodeId> topo_cache_;
    mutable bool topo_dirty_{true};

    void compute_topo_order() const;
};

// ============================================================
// GraphBuilder — fluent DSL for constructing a ComputeGraph.
// ============================================================
class GraphBuilder {
public:
    explicit GraphBuilder(ComputeGraph& graph);

    // Declare an input tensor (symbolic dims supported).
    TensorId input(SymbolicShape shape, DType dtype, std::string name = "");

    // --- Primitive ops ---
    TensorId matmul(TensorId a, TensorId b, std::string name = "");
    TensorId add(TensorId a, TensorId b, std::string name = "");
    TensorId mul(TensorId a, TensorId b, std::string name = "");
    TensorId rms_norm(TensorId x, TensorId weight, float eps = 1e-5f, std::string name = "");
    TensorId layer_norm(TensorId x, TensorId w, TensorId b, float eps = 1e-5f, std::string name = "");
    TensorId softmax(TensorId x, int axis = -1, std::string name = "");
    TensorId silu(TensorId x, std::string name = "");
    TensorId rope(TensorId x, TensorId freqs, int head_dim, std::string name = "");
    TensorId embedding(TensorId indices, TensorId weight, std::string name = "");
    TensorId reshape(TensorId x, SymbolicShape new_shape, std::string name = "");
    TensorId permute(TensorId x, std::vector<int> perm, std::string name = "");
    TensorId slice(TensorId x, int dim, int64_t start, int64_t end, std::string name = "");
    TensorId cast(TensorId x, DType target_dtype, std::string name = "");

    // Mark output tensors of the graph.
    void output(TensorId id);

private:
    ComputeGraph& graph_;

    TensorId emit_unary(OpType op, TensorId x, AttributeMap attrs, std::string name);
    TensorId emit_binary(OpType op, TensorId a, TensorId b, AttributeMap attrs, std::string name);
};

} // namespace axonforge
